### ISSUE TITLE
UI Tracker for 4.0

### ISSUE THREAD

**Issue by Acidhub** [ShyPixie/steam-tools-ng#2]
Platform: Linux
DE: Gnome 3

* [x] No icon outside code (no dash icon, no desktop/menu icon)
* [x] Deleting SteamTrades ID list in config, do not fallback to "- - - -" in main window
* [x] We need mode explaination on first use, please!

On exit:
```
 --> Steam Tools NG version 0.3.1.dev1 (Made with Girl Power <33)
 --> Copyright (C) 2015 ~ 2018 Lara Maia - <dev@lara.click>
 --> Exiting...
Traceback (most recent call last):
  File "/usr/bin/steam-tools-ng", line 151, in <module>
    event_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1396, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
DesyncInterrupt
```

**Comment by ShyPixie** [comment]
A new setup dialog has been added https://github.com/ShyPixie/steam-tools-ng/commit/e556456ac003b0d73bbc672a469f61d3123317d8 https://github.com/ShyPixie/steam-tools-ng/commit/cb88097338f80ee9e1755f24acaf0e3911ec4395 https://github.com/ShyPixie/steam-tools-ng/commit/73403fc10652fb9f352d43fd9da0f29a61c72fda

1/3

**Comment by ShyPixie** [comment]
1.1/3 new setup dialog (refactoring) https://github.com/ShyPixie/steam-tools-ng/commit/e9f292e06dfb541c945079116c8143ed6ff3e0ac#diff-84bb386fc3bebb26f932c1499b3888f1

1.3/3 dialogs like adb, add_authenticator, and login has been merged in setup dialog

1.5/3 adb is disabled for now because I found some inconsistencies in adb protocol from stlib (wrong return codes, no stderr, etc). The currently implementation is not reliable.

1.7/3 Regressions has been fixed at https://github.com/ShyPixie/steam-tools-ng/commit/be43d01fda3d1c104a67978f01fc5d6bffab437d and https://github.com/ShyPixie/steam-tools-ng/commit/1b708a60970a27400ce2adf6cbca7e51aed678ed
