### ISSUE TITLE
Roadmap to 0.7

### ISSUE THREAD

**Issue by ShyPixie** [ShyPixie/steam-tools-ng#4]
- [x] Add steamgifts support (edb36a983019ab300e48bcdab61a9d685092b5be, 3d8f572fd5ec4b4c5471c756627871f0e7f7004f, 26b1fa71f3e9f754c985ed6014ef0b49bf53431b, 0525b09174bca65a105f70ea4693d5d024b517b7)
- [x] Add card farming support (6b9b6d48bda0c7b6d04c6a5ddb5f8e394a885025, 2b61b2c220f3ffc56ec924702be26502b4360e4d)
- [x] fix linux packages (#3)
- [x] fix translations (a14d674bab26cded321edf748379a6b66da99df7 and 96d61c4effa40f29cdd667e55b2dddb85038e491)
- [x] fix user input confirmation via keyboard (51af9729959439553ea3249bfd39c9f4321f13de)
- [x] fix console modules (34c3d3d7182b8954ecbc9ff8f6bc1d5e4e8bac94, 1233691a596cc3a6a52a6988219baf1d62f14255, 28dfe21fa88a8e622de1185090864db37956ce80)
- [x] update console interface with new modules (**) (0525b09174bca65a105f70ea4693d5d024b517b7, 2b61b2c220f3ffc56ec924702be26502b4360e4d)
- [x] remove ADB support (63d30105aaa2b7fa6ea1ada65998af504837a626 and 42966eb3ffdbae5dc11cdec78417d4d207ca0471)
- [x] Fix plugin grid (67c8237834229327dde8f4bee878a8b1253b71e8)
- [x] Fix exceptions when wrong values are found in config file (b5a40a28c89e09a8a3bc517ffa028c831227488c and 490d1b1741ea2ea991314321f283c5d007cc6896)
- [x] Get rid of `config.Check' decorator (4becf06f7d902d2338267653aea6f7fd7c0372ac)

** why are we doubling the code with two versions (console and gui)?

**Comment by ShyPixie** [comment]
adb support is disabled and really broken now. I think that we must remove adb from STNG completely

what do you think @Acidhub? (no-return decision)

**Comment by Acidhub** [comment]
Remove it, period.

**Comment by ShyPixie** [comment]
https://github.com/ShyPixie/stlib/issues/4

**Comment by ShyPixie** [comment]
@acidhub almost done...

**Comment by ShyPixie** [comment]
fixed by [v0.7](https://github.com/ShyPixie/steam-tools-ng/releases/tag/v0.7)
